version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wallet
      MYSQL_ROOT_PASSWORD: longtran5801
    ports: 
      - '3308:3306'
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
    expose:
      - 3306
    
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
    environment:
      DB_PORT: 3306
      DB_HOST: db
    # depends_on:
    #   - db
